"""AbsActive->Abs is None

Revision ID: 1c96f618994a
Revises: b6056a30cc94
Create Date: 2024-01-09 02:02:42.835253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c96f618994a'
down_revision = 'b6056a30cc94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abs_active', 'abs_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('abs_active_abs_id_fkey', 'abs_active', type_='foreignkey')
    op.create_foreign_key(None, 'abs_active', 'abs', ['abs_id'], ['abs_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abs_active', type_='foreignkey')
    op.create_foreign_key('abs_active_abs_id_fkey', 'abs_active', 'abs', ['abs_id'], ['abs_id'])
    op.alter_column('abs_active', 'abs_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
