"""add row items

Revision ID: 1d95a69efe64
Revises: 9e72df4fa794
Create Date: 2024-02-05 23:44:01.565769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d95a69efe64'
down_revision = '9e72df4fa794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abs', sa.Column('viewer', sa.Integer(), nullable=False))
    op.add_column('abs_active', sa.Column('all_time', sa.Boolean(), nullable=False))
    op.add_column('abs_active', sa.Column('is_up', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abs_active', 'is_up')
    op.drop_column('abs_active', 'all_time')
    op.drop_column('abs', 'viewer')
    # ### end Alembic commands ###
