"""Abs add start end time

Revision ID: 9e72df4fa794
Revises: aeac7b1077e4
Create Date: 2024-01-18 21:01:47.066925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e72df4fa794"
down_revision = "aeac7b1077e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("abs_active", sa.Column("start_time", sa.Time(), nullable=False, server_default="8:00:00"))
    op.add_column("abs_active", sa.Column("end_time", sa.Time(), nullable=False, server_default="18:00:00"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("abs_active", "end_time")
    op.drop_column("abs_active", "start_time")
    # ### end Alembic commands ###
