"""cookies

Revision ID: a58f5c7c893e
Revises: 1c96f618994a
Create Date: 2024-01-15 03:17:22.344825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58f5c7c893e'
down_revision = '1c96f618994a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('cookies_id', sa.UUID(), nullable=False),
    sa.Column('ring', sa.String(), nullable=False),
    sa.Column('boobs', sa.String(), nullable=False),
    sa.Column('pony', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('protected_deals_top_line', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_farpost.user_id'], ),
    sa.PrimaryKeyConstraint('cookies_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookies')
    # ### end Alembic commands ###
