"""Add tg_chat_id to User

Revision ID: aeac7b1077e4
Revises: a58f5c7c893e
Create Date: 2024-01-18 00:26:27.390236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeac7b1077e4'
down_revision = 'a58f5c7c893e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_farpost', sa.Column('tg_chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_farpost', 'tg_chat_id')
    # ### end Alembic commands ###
